_target_: ocl.datasets.WebdatasetDataModule

train_shards: "${oc.env:DATASET_PREFIX}/movi_a/train/shard-{000000..000328}.tar"

train_size: 9703                                                    # TODO

val_shards: "${oc.env:DATASET_PREFIX}/movi_a/val/shard-{000000..000008}.tar"
val_size: 250                                                                     # TODO

# default use val for test (same with movi_c.yaml)
test_shards: "${oc.env:DATASET_PREFIX}/movi_a/val/shard-{000000..000008}.tar"
test_size: 250                                                                    # TODO

use_autopadding: true

extra_keys_to_keep: [instances, segmentations, metadata]
# force_single_worker: true

eval_transforms:
  00_1_rename_fields:
    _target_: ocl.transforms.Map
    transform:
      _target_: ocl.preprocessing.RenameFields
      mapping:
        video: image
        segmentations: mask
    fields: [video, segmentations]
    batch_transform: false

  00_2_adapt_mask_format:
    _target_: ocl.transforms.SimpleTransform
    transforms:
      mask:
        _target_: ocl.preprocessing.IntegerToOneHotMask
        output_axis: -4
        max_instances: 10
        ignore_typical_background: false
    batch_transform: false

train_transforms:
  00_1_rename_fields:
    _target_: ocl.transforms.Map
    transform:
      _target_: ocl.preprocessing.RenameFields
      mapping:
        video: image
    fields: [video]
    batch_transform: false
